version: '3.9'

services:
  web:
    image: saakbar/flask_rest_api:v1
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
    env_file:
      - .env
    command: flask run --host=0.0.0.0
    restart: always
